start application, complete zookeeper and solr rebuild
MITLibraries/mitlib-terraform pull request #215
Opened 2020-10-13 16:34 UTC by eldamit

This commit includes all modifications done for solr and zookeper rebuild and start work for building application.

2020-10-16 13:46 UTC, gravesm requested changes

2020-10-16 13:46 UTC, gravesm commented on apps/rdr/solr_cluster.tf
> +    path    = "/solr/collection1_shard1_replica_n1/admin/ping"
Why isn't this just `/solr/collection1/admin/ping`? That's what the docs suggest it should be.

2020-10-16 16:59 UTC, eldamit commented on apps/rdr/solr_cluster.tf
> +    path    = "/solr/collection1_shard1_replica_n1/admin/ping"
I think this path is because of solrcloud mode. When creating collection in https://github.com/MITLibraries/mitlib-terraform/blob/rdr-dv/apps/rdr/ansible/roles/solr/tasks/main.yaml#L132 
The following collection is created and the collection1 name is collection1_shard1_replica_n1
This is the content of  core_properties file: 
#Written by CorePropertiesLocator
#Fri Oct 09 16:11:15 UTC 2020
numShards=1
collection.configName=collection1
name=collection1_shard1_replica_n1
replicaType=NRT
shard=shard1
collection=collection1
coreNodeName=core_node2

2020-10-16 17:08 UTC, eldamit commented on apps/rdr/ansible/roles/solr/tasks/main.yaml
> +    "{{ dataverse.solr.root }}"/bin/solr create_collection -c collection1 -d "{{ dataverse.solr.root }}"/server/solr/collection1/conf/  -V
Currently If collection already exists the ansible task fails with error that collection already exists.  
I will look into filtering the message and do ignore fail if it matches "collection already exists".

2020-10-16 17:14 UTC, eldamit commented on apps/rdr/ansible/roles/solr/tasks/main.yaml
> +    - { src: schema_dv_mdb_fields.xml, dest: "{{ dataverse.solr.root }}/server/solr/collection1/conf"}
yes, they are files, I had those in the files folder initially, but the file module was failing without a good reason using with_items, while template module was not.

2020-10-16 17:45 UTC, eldamit commented on apps/rdr/files/efs_solrs_setup.sh
> +sudo mount -a -t nfs4
I have created the efs with terraform and so far haven't found a good way of passing terraform variables to ansible to run the script is in ansible. The log for is at /var/log/cloud_init. Have rebuild several times without failing. 

But agree can use ansible efs_module to create the efs and that will allow to see errors while executing. I am not sure if can totally avoid hardcoding values though.

2020-10-16 18:37 UTC, eldamit commented on apps/rdr/solr_cluster.tf
> +    path    = "/solr/collection1_shard1_replica_n1/admin/ping"
Actually ping returns ok for /solr/collection1/admin/ping. Making the change.

2020-10-23 15:12 UTC, gravesm commented on apps/rdr/ansible/roles/solr/tasks/main.yaml
> +    - { src: schema_dv_mdb_fields.xml, dest: "{{ dataverse.solr.root }}/server/solr/collection1/conf"}
Try using the copy module instead.

2020-10-23 16:17 UTC, eldamit commented on apps/rdr/files/efs_solrs_setup.sh
> +sudo mount -a -t nfs4
made the change

2020-10-23 17:05 UTC, eldamit commented on apps/rdr/ansible/roles/solr/tasks/main.yaml
> +    - { src: schema_dv_mdb_fields.xml, dest: "{{ dataverse.solr.root }}/server/solr/collection1/conf"}
made the change

2020-10-23 18:07 UTC, eldamit commented on apps/rdr/ansible/roles/solr/tasks/main.yaml
> +    "{{ dataverse.solr.root }}"/bin/solr create_collection -c collection1 -d "{{ dataverse.solr.root }}"/server/solr/collection1/conf/  -V
made change

2020-10-23 18:40 UTC, gravesm approved these changes

2020-10-23 18:49 UTC, gravesm approved these changes

2020-10-23 18:55 UTC, merged